name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Ensure jobs fail fast
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck curl unzip

    - name: Install shellspec
      run: |
        curl -fsSL https://git.io/shellspec | sh -s -- --yes
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Run tests
      run: |
        shellspec spec/

    - name: Run shellcheck
      run: |
        find . -name "*.sh" -not -path "./.git/*" -not -path "./spec/*" -exec shellcheck {} \;

    - name: Test installation script
      run: |
        bash scripts/install.sh help

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and package
      run: |
        bash scripts/build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bash-lib-package
        path: dist/
