name: Release Workflow

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and package
      run: |
        bash scripts/build.sh ${{ github.event.release.tag_name }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: |
          dist/bash-lib-${{ github.event.release.tag_name }}.tar.gz
          dist/bash-lib-${{ github.event.release.tag_name }}.zip
          dist/bash-lib.rb
        draft: false
        prerelease: false
